stages:
  - deploy

deploy-master:
  stage: deploy

  script:
    - ssh root@svps573722.ovh.net "
      cd /var/www/ &&
      cd quaidessavoirfaire &&
      git checkout . &&
      git checkout master &&
      git pull &&
      "